--------------------------------------------------------
--  파일이 생성됨 - 수요일-12월-18-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_LOGIN
--------------------------------------------------------

  CREATE TABLE "PARK"."T_LOGIN" 
   (	"ID" NUMBER(*,0), 
	"USERID" VARCHAR2(30 BYTE), 
	"USERPWD" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_SUBJECT
--------------------------------------------------------

  CREATE TABLE "PARK"."T_SUBJECT" 
   (	"ID" NUMBER(*,0), 
	"SUBJECT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_USER_SUBJECT
--------------------------------------------------------

  CREATE TABLE "PARK"."T_USER_SUBJECT" 
   (	"ID" NUMBER(*,0), 
	"EDUNUM" NUMBER(*,0), 
	"SUBJECT" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table T_USERINFO
--------------------------------------------------------

  CREATE TABLE "PARK"."T_USERINFO" 
   (	"ID" NUMBER(*,0), 
	"USERID" VARCHAR2(30 BYTE), 
	"EDUNUM" NUMBER(*,0), 
	"NAME" VARCHAR2(20 BYTE), 
	"BIRTH" VARCHAR2(30 BYTE), 
	"EMAIL" VARCHAR2(40 BYTE), 
	"PHONE" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into PARK.T_LOGIN
SET DEFINE OFF;
Insert into PARK.T_LOGIN (ID,USERID,USERPWD) values (2,'park','1429');
REM INSERTING into PARK.T_SUBJECT
SET DEFINE OFF;
Insert into PARK.T_SUBJECT (ID,SUBJECT) values (1,'C#');
Insert into PARK.T_SUBJECT (ID,SUBJECT) values (2,'Oracle');
Insert into PARK.T_SUBJECT (ID,SUBJECT) values (3,'Spring');
Insert into PARK.T_SUBJECT (ID,SUBJECT) values (4,'Jsp');
Insert into PARK.T_SUBJECT (ID,SUBJECT) values (5,'Javascript');
Insert into PARK.T_SUBJECT (ID,SUBJECT) values (6,'C++');
Insert into PARK.T_SUBJECT (ID,SUBJECT) values (7,'Android');
REM INSERTING into PARK.T_USER_SUBJECT
SET DEFINE OFF;
Insert into PARK.T_USER_SUBJECT (ID,EDUNUM,SUBJECT) values (9,201407047,'Oracle');
Insert into PARK.T_USER_SUBJECT (ID,EDUNUM,SUBJECT) values (10,201407047,'C#');
REM INSERTING into PARK.T_USERINFO
SET DEFINE OFF;
Insert into PARK.T_USERINFO (ID,USERID,EDUNUM,NAME,BIRTH,EMAIL,PHONE) values (2,'park',201407047,'박문순','1995-11-18','yoroo7130@oracle.co.com','010-4723-1429');
